spring.neo4j.uri=bolt://127.0.0.1:7687/
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=our_password_v1
spring.neo4j.connection-timeout=45m
spring.neo4j.pool.max-connection-lifetime=1h

server.address=127.0.0.1
server.port=8080

cors.allowed.origins=https://mbahara.github.io,http://localhost:5500,http://127.0.0.1:5500,null